name = "Sandstorm Properties"
description = "A mod that allow customize basic sandstorm properties."
author = "JD The Ripper PC"
version = "1.0"

--forumthread = ""

api_version = 10

dont_starve_compatible = false
reign_of_giants_compatible = false
dst_compatible = true
all_clients_require_mod = true

icon_atlas = "modicon.xml"
icon = "modicon.tex"

server_filter_tags = { "sandstorm_properties" }

configuration_options =
{
    {
        name = "sandstorm_oasis_radius",
        label = "Sandstorm oasis radius",
        options = {
            {description = "0", data = 0},
            {description = "1", data = 1},
            {description = "2", data = 2},
            {description = "3", data = 3},
            {description = "4", data = 4},
            {description = "5", data = 5},
            {description = "6", data = 6},
            {description = "7", data = 7},
            {description = "8", data = 8},
            {description = "9", data = 9},
            {description = "10", data = 10},
            {description = "11", data = 11},
            {description = "12", data = 12},
            {description = "13", data = 13},
            {description = "14", data = 14},
            {description = "15", data = 15},
            {description = "16", data = 16},
            {description = "17", data = 17},
            {description = "18", data = 18},
            {description = "19", data = 19},
            {description = "20", data = 20},
            {description = "21", data = 21},
            {description = "22", data = 22},
            {description = "23", data = 23},
            {description = "24", data = 24},
            {description = "25", data = 25},
            {description = "26", data = 26},
            {description = "27", data = 27},
            {description = "28", data = 28},
            {description = "29", data = 29},
            {description = "30", data = 30},
            {description = "31", data = 31},
            {description = "32", data = 32},
            {description = "33", data = 33},
            {description = "34", data = 34},
            {description = "35", data = 35},
            {description = "36", data = 36},
            {description = "37", data = 37},
            {description = "38", data = 38},
            {description = "39", data = 39},
            {description = "40", data = 40},
            {description = "41", data = 41},
            {description = "42", data = 42},
            {description = "43", data = 43},
            {description = "44", data = 44},
            {description = "45", data = 45},
            {description = "46", data = 46},
            {description = "47", data = 47},
            {description = "48", data = 48},
            {description = "49", data = 49},
            {description = "50", data = 50},
            {description = "51", data = 51},
            {description = "52", data = 52},
            {description = "53", data = 53},
            {description = "54", data = 54},
            {description = "55", data = 55},
            {description = "56", data = 56},
            {description = "57", data = 57},
            {description = "58", data = 58},
            {description = "59", data = 59},
            {description = "60", data = 60},
            {description = "61", data = 61},
            {description = "62", data = 62},
            {description = "63", data = 63},
            {description = "64", data = 64},
            {description = "65", data = 65},
            {description = "66", data = 66},
            {description = "67", data = 67},
            {description = "68", data = 68},
            {description = "69", data = 69},
            {description = "70", data = 70},
            {description = "71", data = 71},
            {description = "72", data = 72},
            {description = "73", data = 73},
            {description = "74", data = 74},
            {description = "75", data = 75},
            {description = "76", data = 76},
            {description = "77", data = 77},
            {description = "78", data = 78},
            {description = "79", data = 79},
            {description = "80", data = 80},
            {description = "81", data = 81},
            {description = "82", data = 82},
            {description = "83", data = 83},
            {description = "84", data = 84},
            {description = "85", data = 85},
            {description = "86", data = 86},
            {description = "87", data = 87},
            {description = "88", data = 88},
            {description = "89", data = 89},
            {description = "90", data = 90},
            {description = "91", data = 91},
            {description = "92", data = 92},
            {description = "93", data = 93},
            {description = "94", data = 94},
            {description = "95", data = 95},
            {description = "96", data = 96},
            {description = "97", data = 97},
            {description = "98", data = 98},
            {description = "99", data = 99},
            {description = "100", data = 100},
        },
        default = 1,
    },

    {
        name = "sandstorm_fully_entered_depth",
        label = "Sandstorm fully entered depth",
        options = {
            {description = "0", data = 0},
            {description = "1", data = 1},
            {description = "2", data = 2},
            {description = "3", data = 3},
            {description = "4", data = 4},
            {description = "5", data = 5},
            {description = "6", data = 6},
            {description = "7", data = 7},
            {description = "8", data = 8},
            {description = "9", data = 9},
            {description = "10", data = 10},
            {description = "11", data = 11},
            {description = "12", data = 12},
            {description = "13", data = 13},
            {description = "14", data = 14},
            {description = "15", data = 15},
            {description = "16", data = 16},
            {description = "17", data = 17},
            {description = "18", data = 18},
            {description = "19", data = 19},
            {description = "20", data = 20},
            {description = "21", data = 21},
            {description = "22", data = 22},
            {description = "23", data = 23},
            {description = "24", data = 24},
            {description = "25", data = 25},
            {description = "26", data = 26},
            {description = "27", data = 27},
            {description = "28", data = 28},
            {description = "29", data = 29},
            {description = "30", data = 30},
            {description = "31", data = 31},
            {description = "32", data = 32},
            {description = "33", data = 33},
            {description = "34", data = 34},
            {description = "35", data = 35},
            {description = "36", data = 36},
            {description = "37", data = 37},
            {description = "38", data = 38},
            {description = "39", data = 39},
            {description = "40", data = 40},
            {description = "41", data = 41},
            {description = "42", data = 42},
            {description = "43", data = 43},
            {description = "44", data = 44},
            {description = "45", data = 45},
            {description = "46", data = 46},
            {description = "47", data = 47},
            {description = "48", data = 48},
            {description = "49", data = 49},
            {description = "50", data = 50},
            {description = "51", data = 51},
            {description = "52", data = 52},
            {description = "53", data = 53},
            {description = "54", data = 54},
            {description = "55", data = 55},
            {description = "56", data = 56},
            {description = "57", data = 57},
            {description = "58", data = 58},
            {description = "59", data = 59},
            {description = "60", data = 60},
            {description = "61", data = 61},
            {description = "62", data = 62},
            {description = "63", data = 63},
            {description = "64", data = 64},
            {description = "65", data = 65},
            {description = "66", data = 66},
            {description = "67", data = 67},
            {description = "68", data = 68},
            {description = "69", data = 69},
            {description = "70", data = 70},
            {description = "71", data = 71},
            {description = "72", data = 72},
            {description = "73", data = 73},
            {description = "74", data = 74},
            {description = "75", data = 75},
            {description = "76", data = 76},
            {description = "77", data = 77},
            {description = "78", data = 78},
            {description = "79", data = 79},
            {description = "80", data = 80},
            {description = "81", data = 81},
            {description = "82", data = 82},
            {description = "83", data = 83},
            {description = "84", data = 84},
            {description = "85", data = 85},
            {description = "86", data = 86},
            {description = "87", data = 87},
            {description = "88", data = 88},
            {description = "89", data = 89},
            {description = "90", data = 90},
            {description = "91", data = 91},
            {description = "92", data = 92},
            {description = "93", data = 93},
            {description = "94", data = 94},
            {description = "95", data = 95},
            {description = "96", data = 96},
            {description = "97", data = 97},
            {description = "98", data = 98},
            {description = "99", data = 99},
            {description = "100", data = 100},
        },
        default = 20,
    },

    {
        name = "sandstorm_full_level",
        label = "Sandstorm full level",
        options = {
            {description = "0", data = 0},
            {description = "0.1", data = 0.1},
            {description = "0.2", data = 0.2},
            {description = "0.3", data = 0.3},
            {description = "0.4", data = 0.4},
            {description = "0.5", data = 0.5},
            {description = "0.6", data = 0.6},
            {description = "0.7", data = 0.7},
            {description = "0.8", data = 0.8},
            {description = "0.9", data = 0.9},
            {description = "1", data = 1},
            {description = "Disable", data = 1.1},
        },
        default = 0.7,
    },

    {
        name = "sandstorm_speed_mod",
        label = "Sandstorm speed mod",
        options = {
            {description = "0.0 (no move)", data = 0},
            {description = "0.1", data = 0.1},
            {description = "0.2", data = 0.2},
            {description = "0.3", data = 0.3},
            {description = "0.4", data = 0.4},
            {description = "0.5", data = 0.5},
            {description = "0.6", data = 0.6},
            {description = "0.7", data = 0.7},
            {description = "0.8", data = 0.8},
            {description = "0.9", data = 0.9},
            {description = "1.0 (no effect)", data = 1},
            {description = "1.1", data = 1.1},
            {description = "1.2", data = 1.2},
            {description = "1.3", data = 1.3},
            {description = "1.4", data = 1.4},
            {description = "1.5", data = 1.5},
            {description = "1.6", data = 1.6},
            {description = "1.7", data = 1.7},
            {description = "1.8", data = 1.8},
            {description = "1.9", data = 1.9},
            {description = "2.0", data = 2.0},
            {description = "2.1", data = 2.1},
            {description = "2.2", data = 2.2},
            {description = "2.3", data = 2.3},
            {description = "2.4", data = 2.4},
            {description = "2.5", data = 2.5},
            {description = "2.6", data = 2.6},
            {description = "2.7", data = 2.7},
            {description = "2.8", data = 2.8},
            {description = "2.9", data = 2.9},
            {description = "3.0", data = 3.0},
            {description = "3.1", data = 3.1},
            {description = "3.2", data = 3.2},
            {description = "3.3", data = 3.3},
            {description = "3.4", data = 3.4},
            {description = "3.5", data = 3.5},
            {description = "3.6", data = 3.6},
            {description = "3.7", data = 3.7},
            {description = "3.8", data = 3.8},
            {description = "3.9", data = 3.9},
            {description = "4.0", data = 4.0},
        },
        default = 0.4,
    },
}
